#### Библиотеки

In [1]:
from function_py import texts_to_padded, norm_spectr, spectrogram_to_audio, pd, os, Tokenizer, np, pad_sequences, wavfile, librosa, Sequential, Dense, Reshape  

# Загружали дата фрейм с аудио и преобразованием аудио

In [2]:
dataframe = pd.DataFrame()

path = './audio/'
path_for_data = './numpy_data/'



for name in sorted(os.listdir(path)):
    new_row = {'audio':name[:-4], 'numpy': np.load(f'./numpy_data/{name[:-3]+"npy"}')}
    dataframe = pd.concat([dataframe, pd.DataFrame([new_row])], ignore_index=True)

pd.Series({'audio':name, 'numpy': str(name[-3] + 'npy')})

audio    сожру.wav
numpy         wnpy
dtype: object

# Преобразовывали предложения в цифры

In [3]:
# Sample text data
texts = ['А Агаю', 'А вот и нет.', 'А ну быстро сюда!', 'А-а-а, свежее мясо!', 'А-а-а', 'Ага, иду.', 'Ага', 'Ах ты мелкий...', 'Бессмертие!', 'Блинк дагер!', 'Будешь красоткой с яблоком во рту!', 'Будто одного меня было мало.', 'В кучу!', 'В самом расцвете сил.', 'Вангвард!', 'Вдохни поглубже!', 'Вот и за мной пришли.', 'Враг ушел с верхней линии!', 'Враг ушел с нижней линии!', 'Враг ушел с центральной линии!', 'Время нарезать!', 'Всё в кишках, красота!', 'Вы поглядите, сколько сочного мяса вокруг!', 'Выпотрошить!', 'Давай к делу!', 'Давно пора!', 'Дай освежую... я быстро!', 'Дай подправлю тебе фигуру!', 'Двойной урон!', 'Дело в шляпе!!', 'Дело в шляпе!', 'Дышите глубже, ребята!', 'Жадина-говядина, я такой.', 'Иллюзия!', 'Какой симпатичный фарш!', 'Ко мне-е-е-е!', 'Кому свежих рёбрышек.', 'Кто ребро потерял. Моё будет.', 'Люблю внезапность не приходится чистить кишки вручную.', 'Люблю сокращать чужие калории.', 'М-м, вот это я понимаю - свежий воздух!', 'М-м-ах-м-м', 'М-м-ах-м', 'М-м-м, свежее мясо!', 'М-м-м, устрой лёгким праздник!', 'М-м-м-м', 'М-м', 'Мешки плоти.', 'Милый запах, чё', 'Моё!', 'Мэ-э-э.', 'На верную смерть - это ко мне!', 'На кого замахиваешься!', 'На кусочки!', 'Не пропадать же добру.', 'Не стану тратить всё и сразу.', 'Не твое!', 'Не тут-то было!', 'Не устоял!', 'Не-а!', 'Не-е-ет!', 'Не-е-ет.', 'Невидимость!', 'О, свежее мясо!', 'од топор-р-р!', 'Ой!', 'Ой-ой-ой.', 'Ой... это я что ли', 'Освежую, шмакодявка.', 'Отличная заточка.', 'Отложу, авось пригодится.', 'Падж заждался !', 'Падж тебя приголубит!', 'Пайп оф Инсайт!', 'Паршивый волшебник!!', 'Паршивый волшебник!', 'Первая кровь! У меня ничего в зубах не застряло', 'Перед смертью не надышишься.', 'Подам тебя с криповым соусом!', 'Познакомимся поближе.', 'Поймал!', 'Получай!', 'Порежьте меня на кусочки, я бы сделал для вас то же самое.', 'Последний кусок - мне.', 'Припасу на потом.', 'Пшёл с дороги!', 'Р-р-расчехляю ножи!', 'Резать, рубить!', 'Рублю с двойным усердием!', 'Руки в крови - это про меня.', 'Самое время!', 'Свежее мясо!!!', 'Свежее мясо!!', 'Свежее мясо!', 'Свежее мясо.', 'Свежее мясо', 'Скоростная мясорубка!', 'Слезь!', 'Сожру с потрохами!', 'сожру', 'Солнце уходит на запад, а я остаюсь!', 'Спасёт от передряги.', 'Сюда, быстро!', 'Так пир или... чума!', 'Так тебе и надо!', 'Тип того', 'Туда так туда', 'Тушку мне!', 'Ты ничего не почувствуешь!', 'Ты сегодня без ужина!', 'Тэ-э.', 'У меня уже топор чешется!', 'Урн оф Шадоувс!', 'Ускорение!', 'Форс стафф!', 'Ха-а-а! Свежее мясо!', 'Ха-а', 'Ха-ха! Свежее мясо!', 'Ха-ха, бессмертие!', 'Ха', 'Харт оф тараск!', 'Хе-хе хе', 'Хе-хе-хе-хе-хе-хе-хе, свежее мясо!!', 'Хе-хе-хе-хе-хе-хе-хе, свежее мясо!', 'Хе-хе-хе-хе. Свежее мясо.', 'Хе-хе-хе-хе. Свежее мясо', 'Хе-хе-хе-хе', 'Хм-м, попробуй жизнь на вкус!', 'Хорошая заточка.', 'Худ оф Дефайнс!', 'Хы-хы-ха-ха, ты погляди, свежее мясо!', 'Хы-хы-хы-хы, свежее мясо!', 'Хы-хы-хы-хы, у тебя рёбра отвалились!', 'Хэх, хе-хе-хе-хе-хе, не твоё!', 'Чёрт, давно пора!', 'Чёрта... с два.', 'Чёрта... с два', 'Чёртовы крипы.', 'Что протухло', 'Что-то я... проголодался.', 'Шивас Гвардс!', 'Э-э-э.', 'Э-э.', 'Эй!', 'Эй, ты.', 'Эй', 'Это кто зашел на ужин', 'Эх.', 'Я ж ещё... не дорезал.', 'Я специально, честно...', 'Я что-то не то съел']

# Text normalization and tokenization

tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n')
tokenizer.fit_on_texts(texts)

padded_texts = texts_to_padded(texts, tokenizer)

# Vocabulary size
vocab_size = len(tokenizer.word_index) + 1

# Print the preprocessed data
#print("Normalized Texts:", normalized_texts)
print("Padded Texts:\n", padded_texts)

Padded Texts:
 [[  6  66   0 ...   0   0   0]
 [  6  25  20 ...   0   0   0]
 [  6  68  26 ...   0   0   0]
 ...
 [  8 261 262 ...   0   0   0]
 [  8 264 265 ...   0   0   0]
 [  8  23  18 ...   0   0   0]]


# Загружаем спектрограмму 

In [4]:
spectrograms = [np.load(f'./numpy_data/{file_name}') for file_name in sorted(os.listdir('./numpy_data'))]

ayst = max([i.shape[1] for i in spectrograms])

spectrograms = [norm_spectr(i, ayst) for i in spectrograms]
spectrograms=np.array(spectrograms)



#### Спектрограмму преобразовываем в звук

In [5]:
path_for_data = './numpy_data/'



spectrogram_to_audio(spectrograms[2])

## Создаём нейронную сеть

In [6]:
train_data_x, train_data_y = np.array(padded_texts), np.array(spectrograms)
output_shape = spectrograms[0].shape
model = Sequential()
model.add( Dense(30, input_dim=len(padded_texts[0])) )
for i in range(4):
        model.add( Dense(units=20, activation='LeakyReLU') )
model.add( Dense( output_shape[0]*output_shape[1], activation='LeakyReLU' ) )
model.add( Reshape(output_shape)  )
model.compile(loss='mae', optimizer='adam')
model.fit(train_data_x, train_data_y
                        , epochs=200
                        , batch_size=64
                        , verbose=0
                        ) 


In [9]:
word = ['А ну сюда!']
fraze = texts_to_padded(word, tokenizer)

In [10]:
fraze_spector = model.predict(fraze)

1/1 [==============================] - 0s 112ms/step


In [11]:
spectrogram_to_audio(fraze_spector)

error: ushort format requires 0 <= number <= 65535